[tool.poetry]
name = "python-js-module"
version = "0.0.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
javascript = "^1!1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true

